<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Solid Jogger Jeans with Drawstring</name>
   <tag></tag>
   <elementGuidId>95d3db80-c039-44b8-b7fd-32bfb34e950f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='products']/div[3]/div/div/div[5]/a/div/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>79777056-825e-4883-9a17-544b3213de58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nameCls</value>
      <webElementGuid>acc068f5-fbfb-489e-bab9-7adfc48e25f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Solid Jogger Jeans with Drawstring</value>
      <webElementGuid>dee3e10d-50f7-4d6e-b76e-ab750a2f2753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;products&quot;)/div[@class=&quot;items&quot;]/div[@class=&quot;ReactVirtualized__Grid items&quot;]/div[@class=&quot;ReactVirtualized__Grid__innerScrollContainer&quot;]/div[@class=&quot;item rilrtl-products-list__item item&quot;]/a[@class=&quot;rilrtl-products-list__link&quot;]/div[@class=&quot;preview&quot;]/div[@class=&quot;contentHolder&quot;]/div[@class=&quot;nameCls&quot;]</value>
      <webElementGuid>598e8f7f-641a-4139-80eb-032e1671b7e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='products']/div[3]/div/div/div[5]/a/div/div[2]/div[2]</value>
      <webElementGuid>0f354f80-4d55-403e-a07b-58fbd9355403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='iVOC'])[1]/following::div[1]</value>
      <webElementGuid>1f3842ea-be91-4ed8-bbae-71dc3715c190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quick View'])[5]/following::div[3]</value>
      <webElementGuid>9adcc0a5-09b3-4671-a78b-9427cb401c2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹1,025'])[1]/preceding::div[1]</value>
      <webElementGuid>4bb6d958-6267-49c7-b973-c63cd1596c56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹1,799'])[1]/preceding::div[1]</value>
      <webElementGuid>2f182e67-f4c2-4c92-a588-2abfa7bb2dea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Solid Jogger Jeans with Drawstring']/parent::*</value>
      <webElementGuid>4aefa8cc-8b72-4936-a1b4-23bedd1724a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a/div/div[2]/div[2]</value>
      <webElementGuid>54748eae-0b48-4447-bd2e-f9577a431ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Solid Jogger Jeans with Drawstring' or . = 'Solid Jogger Jeans with Drawstring')]</value>
      <webElementGuid>33d6d7e9-30ad-4143-9517-7178e3ec62ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
