<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_APPLE iPhone 13 (Starlight, 128 GB)</name>
   <tag></tag>
   <elementGuidId>9cd7c105-f224-45b2-8c27-c4546eed4d19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.B_NuCI</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div[3]/div/div[2]/div[2]/div/div/h1/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>db173036-58b0-42be-9dc2-28ab907a62a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>B_NuCI</value>
      <webElementGuid>2416727e-b76e-463c-8396-927b52a5685e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>APPLE iPhone 13 (Starlight, 128 GB)</value>
      <webElementGuid>67a16de8-b720-42d8-9bcb-a10fc4b878a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;_2c7YLP UtUXW0 _6t1WkM _3HqJxg&quot;]/div[@class=&quot;_1YokD2 _2GoDe3&quot;]/div[@class=&quot;_1YokD2 _3Mn1Gg col-8-12&quot;]/div[@class=&quot;_1AtVbE col-12-12&quot;]/div[@class=&quot;aMaAEs&quot;]/div[1]/h1[@class=&quot;yhB1nd&quot;]/span[@class=&quot;B_NuCI&quot;]</value>
      <webElementGuid>c6ef684e-bba3-4662-9247-1894a37a0fb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[3]/div/div[2]/div[2]/div/div/h1/span</value>
      <webElementGuid>40059c6d-e9c4-486f-84d9-47f218926aca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share'])[1]/following::span[1]</value>
      <webElementGuid>e0b21add-4a72-4f6b-a7b1-38374fa68fab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Compare'])[1]/following::span[4]</value>
      <webElementGuid>4f2adaee-b22d-40c5-b8a8-e23dc357c8e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&amp;'])[1]/preceding::span[3]</value>
      <webElementGuid>ef787b7e-a80c-4f18-842a-a1cf24725776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Extra ₹7901 off'])[1]/preceding::span[8]</value>
      <webElementGuid>97254e82-f768-498f-b2c5-c45bff64ed0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/span</value>
      <webElementGuid>e0574d1d-8c68-4524-9ba9-7b580a95fb19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'APPLE iPhone 13 (Starlight, 128 GB)' or . = 'APPLE iPhone 13 (Starlight, 128 GB)')]</value>
      <webElementGuid>5ef06a0e-258e-4e74-b321-1fc6a7015777</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
