<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_30</name>
   <tag></tag>
   <elementGuidId>24848944-ea4b-4d8f-bc8a-0f27492aad2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='appContainer']/div[2]/div/div/div[3]/div/div[3]/div/div[6]/div[3]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4b1cabe2-1aa7-4bba-ac4d-15cf9b88b282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>72217bee-ffe0-4410-98af-5c4c06bb7aec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appContainer&quot;)/div[@class=&quot;content&quot;]/div[1]/div[@class=&quot;main-view product-view false&quot;]/div[@class=&quot;prod-container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-4&quot;]/div[@class=&quot;prod-content&quot;]/div[@class=&quot;size-variant-block&quot;]/div[@class=&quot;size-swatch&quot;]/div[@class=&quot;circle size-variant-item size-instock&quot;]/span[1]</value>
      <webElementGuid>4312e87e-438d-449e-88fe-0585d461d829</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='appContainer']/div[2]/div/div/div[3]/div/div[3]/div/div[6]/div[3]/div/span</value>
      <webElementGuid>9f4ee1e4-bbbd-4226-97a9-41bc4fc3599d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View All Products>'])[1]/following::span[2]</value>
      <webElementGuid>c57e2b49-5bf3-43af-8690-d6c253e97a9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEW'])[5]/preceding::span[5]</value>
      <webElementGuid>cada3d74-2d5c-4dd5-9c38-dbfb6a154526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='30']/parent::*</value>
      <webElementGuid>3ffb1670-fadf-484b-9827-a381799f231f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[3]/div/span</value>
      <webElementGuid>3563e706-0a54-47fb-9608-b783eef349ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '30' or . = '30')]</value>
      <webElementGuid>d5e020bc-ee1f-4645-9acc-302070c8b930</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
