<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email or phone number_email-or-phone</name>
   <tag></tag>
   <elementGuidId>1b6db2ae-67d1-41ac-b877-37a6ceed13e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#email-or-phone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='email-or-phone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3fd62e29-7e08-4c52-b85c-151a3cd7a127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input__input</value>
      <webElementGuid>c70afb94-ddc8-41a0-9847-9ed2c0389665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email-or-phone</value>
      <webElementGuid>750f2cb7-727d-4b6d-b2a7-54f31e591bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d85aedef-c4aa-43e1-a028-07c89d4b5ad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email-or-phone</value>
      <webElementGuid>ed1f8be2-b51c-4b75-813c-0363e965404f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email or phone number</value>
      <webElementGuid>6601f29c-e32c-4baf-9916-4be2f7dd0298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-artdeco-is-focused</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fe5f09b5-c02f-4ced-8c06-df799aa6f34d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email-or-phone&quot;)</value>
      <webElementGuid>d3e91b56-521c-4224-9f6a-6f1c0c29a685</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='email-or-phone']</value>
      <webElementGuid>81ee19a8-1b98-445e-b3f7-ca859380161c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>85da86e4-d2f5-49bb-ad43-e6dedad32ec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'email-or-phone' and @type = 'text' and @name = 'email-or-phone' and @placeholder = 'Email or phone number']</value>
      <webElementGuid>287472a5-57d1-4706-b7e5-23262d4e9b1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
