<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>76f4566d-f540-4604-a9d3-1fe96b180854</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a._1_3w1N</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div/div/div[2]/div[3]/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>74b56087-04d6-4a92-b425-38224416f2e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1_3w1N</value>
      <webElementGuid>42ce9084-6f38-4b88-b6fa-677b290af8fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/account/login?ret=/search%3Fq%3Diphone+13%26sid%3Dtyy%252C4io%26as%3Don%26as-show%3Don%26otracker%3DAS_QueryStore_OrganicAutoSuggest_1_3_na_na_ps%26otracker1%3DAS_QueryStore_OrganicAutoSuggest_1_3_na_na_ps%26as-pos%3D1%26as-type%3DRECENT%26suggestionId%3Diphone+13%257CMobiles%26requestId%3D033aeca9-60a0-46ad-b869-f50da541a93e%26as-searchtext%3Diph</value>
      <webElementGuid>72d4a852-92c6-4ae3-b371-8e9583e6c9af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>c86b942a-ffba-4a59-8e85-ad821c5a3301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;_1kfTjk&quot;]/div[@class=&quot;_1rH5Jn&quot;]/div[@class=&quot;_2Xfa2_&quot;]/div[@class=&quot;go_DOp _2errNR&quot;]/div[@class=&quot;_28p97w&quot;]/div[@class=&quot;_1psGvi _3BvnxG&quot;]/div[1]/a[@class=&quot;_1_3w1N&quot;]</value>
      <webElementGuid>67ba6b82-2926-42c5-b1dc-233171cd41f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div/div/div[2]/div[3]/div/div/div/a</value>
      <webElementGuid>69aa60c5-b35b-408e-a57b-27e7c986b865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Login')]</value>
      <webElementGuid>a15253d0-46a7-4926-9efa-429639b1f08e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plus'])[1]/following::a[1]</value>
      <webElementGuid>60f5a333-c93f-4cef-9b86-57c151cf67aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up'])[1]/preceding::a[1]</value>
      <webElementGuid>947ba353-e6f7-46b6-be5c-757ec7475b04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>53d67981-baef-416b-a7a2-8d4239fd2fe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/account/login?ret=/search%3Fq%3Diphone+13%26sid%3Dtyy%252C4io%26as%3Don%26as-show%3Don%26otracker%3DAS_QueryStore_OrganicAutoSuggest_1_3_na_na_ps%26otracker1%3DAS_QueryStore_OrganicAutoSuggest_1_3_na_na_ps%26as-pos%3D1%26as-type%3DRECENT%26suggestionId%3Diphone+13%257CMobiles%26requestId%3D033aeca9-60a0-46ad-b869-f50da541a93e%26as-searchtext%3Diph')]</value>
      <webElementGuid>cc10480e-bfee-4c7a-9d6a-08350a3550ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/a</value>
      <webElementGuid>7927ac29-0433-48ca-a425-279c01238ef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/account/login?ret=/search%3Fq%3Diphone+13%26sid%3Dtyy%252C4io%26as%3Don%26as-show%3Don%26otracker%3DAS_QueryStore_OrganicAutoSuggest_1_3_na_na_ps%26otracker1%3DAS_QueryStore_OrganicAutoSuggest_1_3_na_na_ps%26as-pos%3D1%26as-type%3DRECENT%26suggestionId%3Diphone+13%257CMobiles%26requestId%3D033aeca9-60a0-46ad-b869-f50da541a93e%26as-searchtext%3Diph' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>6088b415-1241-4638-9fba-36dbe14fc840</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
