<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_APPLE iPhone 13 (Starlight, 128 GB)</name>
   <tag></tag>
   <elementGuidId>39209b3e-d7cc-4851-bb93-9953eb9e49fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div._4rR01T</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div[3]/div/div[2]/div[2]/div/div/div/a/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>972869a6-8304-4a4c-b188-55fbcc73eab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_4rR01T</value>
      <webElementGuid>ee142c5d-3390-4c4f-ab3e-aecb4f441bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>APPLE iPhone 13 (Starlight, 128 GB)</value>
      <webElementGuid>6225a2a9-4249-4d4b-b7ab-290f49dfe426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;_36fx1h _6t1WkM _3HqJxg&quot;]/div[@class=&quot;_1YokD2 _2GoDe3&quot;]/div[@class=&quot;_1YokD2 _3Mn1Gg&quot;]/div[@class=&quot;_1AtVbE col-12-12&quot;]/div[@class=&quot;_13oc-S&quot;]/div[1]/div[@class=&quot;_2kHMtA&quot;]/a[@class=&quot;_1fQZEK&quot;]/div[@class=&quot;_3pLy-c row&quot;]/div[@class=&quot;col col-7-12&quot;]/div[@class=&quot;_4rR01T&quot;]</value>
      <webElementGuid>b3053bd7-5778-41af-a51e-0d3f1f4d574c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[3]/div/div[2]/div[2]/div/div/div/a/div[2]/div/div</value>
      <webElementGuid>8d30f859-dc1a-441d-ab81-597d7502280e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Compare'])[1]/following::div[5]</value>
      <webElementGuid>121eb31b-326e-4551-b3fa-20bc9d65c956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Newest First'])[1]/following::div[16]</value>
      <webElementGuid>ac93f7f6-e427-4e9c-877e-97bc08cc2c81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&amp;'])[1]/preceding::div[2]</value>
      <webElementGuid>073e918a-5a06-4cb3-8fa5-025f772149a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A15 Bionic Chip Processor'])[1]/preceding::div[3]</value>
      <webElementGuid>4a3d27ea-3585-49b3-9258-ccaba057af84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='APPLE iPhone 13 (Starlight, 128 GB)']/parent::*</value>
      <webElementGuid>d314224d-208f-480a-99ea-47c55b03c9c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div[2]/div/div</value>
      <webElementGuid>c9b103cd-0dcc-4a0d-b4d5-d30ab6106971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'APPLE iPhone 13 (Starlight, 128 GB)' or . = 'APPLE iPhone 13 (Starlight, 128 GB)')]</value>
      <webElementGuid>45d07d35-5edf-457c-9031-6f0e5648679b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
