<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_mobiles</name>
   <tag></tag>
   <elementGuidId>4f776f5d-a178-4a01-81e8-b6b250477740</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.lrtEPN</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div/div/div[2]/div[2]/form/ul/li[2]/div/a/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c83a0554-d371-4425-868b-834aea80bfcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lrtEPN</value>
      <webElementGuid>9c124e02-15a4-4b22-8356-cd6801f824ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>mobiles</value>
      <webElementGuid>8b8b2840-3cfa-4265-8cc2-67d9b407e419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;_1kfTjk&quot;]/div[@class=&quot;_1rH5Jn&quot;]/div[@class=&quot;_2Xfa2_&quot;]/div[@class=&quot;_1cmsER&quot;]/form[@class=&quot;_2M8cLY header-form-search&quot;]/ul[@class=&quot;col-12-12 _1MRYA1 _38UFBk&quot;]/li[@class=&quot;Y5N33s&quot;]/div[1]/a[@class=&quot;_3izBDY _3BfqWP&quot;]/div[@class=&quot;lrtEPN&quot;]</value>
      <webElementGuid>86bd9f4e-d0c3-469f-84b2-354f5095825d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div/div/div[2]/div[2]/form/ul/li[2]/div/a/div[2]</value>
      <webElementGuid>e854666c-fcde-4b34-98a2-e6ae6cdf1692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discover More'])[1]/following::div[4]</value>
      <webElementGuid>a1ddc671-cc2d-44d1-9b9e-fe40adf493f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plus'])[1]/following::div[11]</value>
      <webElementGuid>4d51c265-a19d-4503-a1ae-ef712bfd9714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='shoes'])[1]/preceding::div[3]</value>
      <webElementGuid>a35b2ab6-45f8-4711-b5bd-847a0571da22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='t shirts'])[1]/preceding::div[7]</value>
      <webElementGuid>209f600d-fa4d-432d-8a6c-14b7e181aba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='mobiles']/parent::*</value>
      <webElementGuid>70a9821c-bd5b-45c1-b425-3ca6326ac404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div[2]</value>
      <webElementGuid>71382554-1164-42d8-bacb-45f5d630666f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'mobiles' or . = 'mobiles')]</value>
      <webElementGuid>d37e9baf-7524-4292-917d-c9c8f5818d8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
