<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sign In  Join AJIO_ic-close-quickview</name>
   <tag></tag>
   <elementGuidId>0bcf9bd8-b0ef-4c77-b6f0-6d796674f076</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ic-close-quickview</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login-modal']/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>13719658-9cce-4c42-895c-198e36ce476f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ic-close-quickview</value>
      <webElementGuid>0456acbb-0f03-480d-ad98-64ba5f37bc77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-modal&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ic-close-quickview&quot;]</value>
      <webElementGuid>d9357a2d-976d-4097-9648-e7c65c7b6475</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-modal']/div/div/div</value>
      <webElementGuid>531634de-0101-42a5-8830-f37a45e8f829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div/div</value>
      <webElementGuid>3d6b15ee-1306-411a-99e8-22b490627a73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
