<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_23</name>
   <tag></tag>
   <elementGuidId>5b4507d4-8b01-4b8d-a39a-943e050d2dd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[5]/div[2]/div/div[2]/div/div/div[2]/div/div/div/div[2]/div[2]/div[3]/div[4]/div[4]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4810b7c4-0f86-4e7f-9a58-b88e7463d2cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ToDuh e u DDJau</value>
      <webElementGuid>cd73a952-6ed4-4167-9889-af4afac6765f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>23</value>
      <webElementGuid>249d85e5-a079-4ca0-b571-d25da588c6a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BODY_BLOCK_JQUERY_REFLOW&quot;)/div[@class=&quot;KWdaU Za f e&quot;]/div[2]/div[@class=&quot;SKCqA _T R2 f e&quot;]/div[2]/div[@class=&quot;f&quot;]/div[@class=&quot;ELrBW F1 _V&quot;]/div[@class=&quot;ZxKNQ&quot;]/div[@class=&quot;f v _Y G&quot;]/div[@class=&quot;MNzWi&quot;]/div[@class=&quot;rYbqD V&quot;]/div[@class=&quot;rujDD q c&quot;]/div[@class=&quot;SmgvF&quot;]/div[@class=&quot;SWwwt notranslate&quot;]/div[@class=&quot;ZeumR u&quot;]/div[@class=&quot;WiccV&quot;]/div[@class=&quot;ToDuh e u DDJau&quot;]</value>
      <webElementGuid>55a5038d-de76-4f5f-adfe-152850020629</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[5]/div[2]/div/div[2]/div/div/div[2]/div/div/div/div[2]/div[2]/div[3]/div[4]/div[4]/div</value>
      <webElementGuid>2fc67fb8-0c77-4ee5-959f-b742a4e3fae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUN'])[2]/following::div[75]</value>
      <webElementGuid>fac51449-cb9f-4625-8208-8fb439ab9026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SAT'])[2]/following::div[76]</value>
      <webElementGuid>ea37a776-c536-4022-b972-45fb88577250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cheaper'])[1]/preceding::div[30]</value>
      <webElementGuid>8f36988d-ceb6-439f-9435-c0d233a3afee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Average'])[1]/preceding::div[33]</value>
      <webElementGuid>df3db445-07be-49d1-a37c-7e33b3f6bde0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div[4]/div[4]/div</value>
      <webElementGuid>ab5c27f4-4799-42f6-a03d-c8b5e5694976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '23' or . = '23')]</value>
      <webElementGuid>0accf6b6-df8c-4062-af18-bec5ceb25d3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
