<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_12</name>
   <tag></tag>
   <elementGuidId>60e2e5fd-633b-4c91-9b29-fdbc8321a8ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.WiccV.end.selected</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[5]/div[2]/div/div[2]/div/div/div[2]/div/div/div/div[2]/div[2]/div[3]/div[3]/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b993545a-f069-4aed-bf46-9712c222cee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>WiccV end selected</value>
      <webElementGuid>f021d986-046b-486e-9416-547d3848f321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b6b49808-26ac-4893-8f7c-baaba95c7a8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>5f4b93dc-d67f-4b3a-96d6-283d78eace9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Wed Apr 12 2023</value>
      <webElementGuid>fca64b7c-0f4d-4aa1-ad24-52c6bf2e7544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8530f4ae-a2ec-459e-b2fb-829575a12481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0cabf2c8-837d-4066-9396-5a5d5319bcb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>73d98c85-235f-45ee-b5f9-51c404a6fdc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BODY_BLOCK_JQUERY_REFLOW&quot;)/div[@class=&quot;KWdaU Za f e&quot;]/div[2]/div[@class=&quot;SKCqA _T R2 f e&quot;]/div[2]/div[@class=&quot;f&quot;]/div[@class=&quot;ELrBW F1 _V&quot;]/div[@class=&quot;ZxKNQ&quot;]/div[@class=&quot;f v _Y G&quot;]/div[@class=&quot;tXUqa&quot;]/div[@class=&quot;rYbqD V&quot;]/div[@class=&quot;rujDD q c&quot;]/div[@class=&quot;SmgvF&quot;]/div[@class=&quot;SWwwt notranslate&quot;]/div[@class=&quot;ZeumR u&quot;]/div[@class=&quot;WiccV end selected&quot;]</value>
      <webElementGuid>272be284-7283-45d2-946d-1e4d99d0235e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[5]/div[2]/div/div[2]/div/div/div[2]/div/div/div/div[2]/div[2]/div[3]/div[3]/div[3]</value>
      <webElementGuid>2aa4f45a-96c3-46ed-9fb3-588d31892ec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUN'])[2]/following::div[43]</value>
      <webElementGuid>806212cf-8bb4-4e3d-92d5-634ee508d23a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SAT'])[2]/following::div[44]</value>
      <webElementGuid>747f1de0-fc50-40e5-b965-d93ad50f82c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cheaper'])[1]/preceding::div[60]</value>
      <webElementGuid>018970c5-dafe-4556-9ab5-6d322f2af300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Average'])[1]/preceding::div[63]</value>
      <webElementGuid>05519c9f-02d4-42ae-9ec0-910af1e86f94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div[3]/div[3]</value>
      <webElementGuid>ea7b2d61-0096-42c9-a061-9ae5983735c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '12' or . = '12')]</value>
      <webElementGuid>7eced9e9-f11c-4dab-9482-21a8db6978d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
