<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Hotels</name>
   <tag></tag>
   <elementGuidId>f4b8bd9c-cc93-44d5-bcae-78b75bf1190b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.XUWut.Ra._S.z._Z.w.o.v._Y.Wh.k._T.wSSLS</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='lithium-root']/main/div/div/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a45e3075-0e58-495b-98de-9e78cf57b7b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>XUWut Ra _S z _Z w o v _Y Wh k _T wSSLS</value>
      <webElementGuid>76f48fe5-8d0e-457a-a2d2-4cc4fdbdf7c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Hotels</value>
      <webElementGuid>828bd6b6-7903-4ed6-a962-dd5597bd0f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hotels</value>
      <webElementGuid>b574918c-1ffa-4348-b6ef-4167b86b70f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lithium-root&quot;)/main[1]/div[@class=&quot;cBOoN&quot;]/div[@class=&quot;rGQXC _T ivvQp&quot;]/div[@class=&quot;QvCXh mvTrV cyIij fluiI&quot;]/div[@class=&quot;amxpu&quot;]/div[@class=&quot;IvGkt hnsQj pTcNu BhqVp GRfiG jdaPs&quot;]/a[@class=&quot;XUWut Ra _S z _Z w o v _Y Wh k _T wSSLS&quot;]</value>
      <webElementGuid>14f9273c-7aca-4df1-8c38-c0a76755ee3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lithium-root']/main/div/div/div/div/div/a</value>
      <webElementGuid>8a7fffc6-7b8d-482c-91ac-e0407bc02464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basket'])[1]/following::a[1]</value>
      <webElementGuid>d36eee34-2dde-403f-8597-89662b5e18d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/following::a[2]</value>
      <webElementGuid>eb933df8-2778-4d8e-becb-fc2909970b36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Things to Do'])[1]/preceding::a[1]</value>
      <webElementGuid>ca3e94e6-ba3d-4152-ae19-a641e0eb317a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Hotels')]</value>
      <webElementGuid>5d1c685f-99ed-4949-99fd-aa0289dae653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/a</value>
      <webElementGuid>145828e1-0aed-4db5-bed4-88c5e66f76b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Hotels' and (text() = 'Hotels' or . = 'Hotels')]</value>
      <webElementGuid>8e5b7144-83ba-40ec-924a-933f8bc3ef2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
