<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Dubai</name>
   <tag></tag>
   <elementGuidId>e0eab967-f661-4166-b752-61d85ed102dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='typeahead_results']/a[4]/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3550e9f4-faab-4596-a63d-26f20e5b51f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>biGQs _P fiohW fOtGX</value>
      <webElementGuid>ad85b683-a08d-460b-b901-ef5851de31eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dubai</value>
      <webElementGuid>1c43791e-ff78-48b8-a2b5-e2a1b9628d0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;typeahead_results&quot;)/a[@class=&quot;GzJDZ w z _S _F Wc Wh Q B- _G&quot;]/div[@class=&quot;EtzER&quot;]/div[@class=&quot;biGQs _P fiohW fOtGX&quot;]</value>
      <webElementGuid>5e904a58-c34c-48e8-b834-94699156604c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='typeahead_results']/a[4]/div[2]/div</value>
      <webElementGuid>415fc539-3aa1-4b30-9b20-8b945374de93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kerala, India'])[1]/following::div[3]</value>
      <webElementGuid>981f8c58-17e2-4687-863d-c3591ba095d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Munnar'])[1]/following::div[5]</value>
      <webElementGuid>84e3ca14-9f69-4634-ba64-63aacc381467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Emirate of Dubai, United Arab Emirates'])[1]/preceding::div[1]</value>
      <webElementGuid>6cbee84c-dcc6-49b1-898c-6762c8cd3fc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='London'])[1]/preceding::div[4]</value>
      <webElementGuid>6d54c620-956c-4f78-a378-022da32bbf88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dubai']/parent::*</value>
      <webElementGuid>8117c483-a82c-45a7-aefd-74b5f55bbf03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]/div[2]/div</value>
      <webElementGuid>89ae0e43-9297-4569-bc2f-23719417958c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Dubai' or . = 'Dubai')]</value>
      <webElementGuid>383606ab-99d1-4978-8065-5d18dcd66b4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
